version: '3.8'

services:
  backend:
    build: ./app
    container_name: django_backend
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
