# Generated by Django 5.2.3 on 2025-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_product', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
            ],
        ),
    ]
